name: bling_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.7+1

  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1

  google_sign_in: ^7.1.1
  google_fonts: ^6.2.1

  image_picker: ^1.1.2
  exif: ^3.3.0
  photo_view: ^0.15.0
  app_links: ^6.4.1
  share_plus: ^12.0.0
  audioplayers: ^6.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  geoflutterfire_plus: ^0.0.21

  get: ^4.6.6
  uuid: ^4.3.3

  # ▼▼▼▼▼ Google Places API를 위한 패키지 추가 ▼▼▼▼▼
  flutter_google_maps_webservices: ^1.1.1
  
  
  # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.3
  intl: ^0.20.2
  flutter_chip_tags: ^2.0.2
  provider: ^6.1.5
  video_player: ^2.10.0
  visibility_detector: ^0.4.0+2
  cached_network_image: ^3.4.0
  smooth_page_indicator: ^1.2.1
  google_maps_flutter_platform_interface: ^2.14.0
  google_maps_flutter_android: ^2.18.2
  google_maps_flutter_ios: 2.15.5
  http: ^1.5.0
  camera: ^0.11.2
  path_provider: ^2.1.5
  path: ^1.9.1
  cloud_functions: ^6.0.1
  firebase_app_check: ^0.4.1+2
  flutter_riverpod: ^3.0.3
  device_info_plus: ^9.0.0

  # Link handling and rich previews
  url_launcher: ^6.3.0
  any_link_preview: ^3.0.2
  flutter_svg: ^2.2.1
  vector_math: ^2.2.0
  collection: ^1.19.1
  percent_indicator: ^4.2.5
  timeago: ^3.7.1
  async: ^2.13.0
  material_symbols_icons: ^4.2874.0


  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_cloud_firestore: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/ai/ai_rules_v2.json
    - assets/icons/
    - assets/sounds/
    - assets/data/